{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "@Assistant_Sybot",
  "main": "src/index.ts",
  "compatibility_date": "2026-08-08",
  "observability": {
    "enabled": true
  },

  // Add this to your wrangler.jsonc
  "kv_namespaces": [
    {
      "binding": "KV",
      "id": "014aa092b3a349e58383b7fbe495cec0",
      
      // Optional: preview_id used when running wrangler dev for local dev
      "preview_id": "93f8cd58fa693ec493905b7a56866381"
    }
  ]
}
